image:
  repository: datadog/agent
rbac:
  create: true
datadog:
  apiKeyExistingSecret: dd
  name: datadog
  logsEnabled: true
  logsConfigContainerCollectAll: true
  apmEnabled: true
  nonLocalTraffic: true
  processAgentEnabled: true
  confd:
    kube_controller_manager.yaml: |-
      ad_identifiers:
        - kube-controller-manager
      init_config:
      instances:
        - prometheus_url: http://%%host%%:10252/metrics
    kube_scheduler.yaml: |-
      ad_identifiers:
        - kube-scheduler
      init_config:
      instances:
        - prometheus_url: http://%%host%%:10251/metrics
    etcd.yaml: |-
      ad_identifiers:
        - etcd
      init_config:
      instances:
        - use_preview: true
          prometheus_url: https://%%host%%:2379/metrics
          ssl_ca_cert: /etc/kubernetes/pki/etcd/ca.crt
          ssl_cert: /etc/kubernetes/pki/etcd/peer.crt
          ssl_private_key: /etc/kubernetes/pki/etcd/peer.key
  volumes:
    - name: etcd-certs
      hostPath:
        path: /etc/kubernetes/pki/etcd
        type: DirectoryOrCreate
    - name: empty-dir
      emptyDir: {}
  volumeMounts:
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
    - mountPath: /etc/datadog-agent/conf.d/etcd.d
      name: empty-dir
clusterAgent:
  enabled: true
  containerName: cluster-agent
  image:
    repository: datadog/cluster-agent
    tag: latest
  replicas: 1
  tokenExistingSecret: dd
  metricsProvider:
    enabled: false
  clusterChecks:
    enabled: true
  confd:
    nginx_ingress_controller.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: http://nginx-nginx-ingress-controller-metrics:9913/metrics
systemProbe:
  enabled: true
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
daemonset:
  enabled: true
  useHostPort: true
  tolerations:
    - operator: Exists
  useConfigMap: true
  customAgentConfig:
    listeners:
      - name: kubelet
    config_providers:
      - name: kubelet
        polling: true
    apm_config:
      enabled: true
      apm_non_local_traffic: true
      obfuscation:
        - name: "http.url"
          pattern: "Email=[^&]+"
          repl: "Email=?"
        - name: "http.url"
          pattern: "customerId=[^&]+"
          repl: "customerId=?"
    jmx_use_cgroup_memory_limit: true

